export Statistics from './Statistics';
export Datamenu from './Datamenu';
export Bimdata from './Bimdata';
export Apiservice from './Apiservice';
export Application from './Application';
export Platformplugins from './Platformplugins';
export News from './News';
export Regulation from './Regulation';
export Pricedata from './Pricedata';